import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
EXPIRATION_TIME = int(os.getenv("EXPIRATION_TIME"))
REFRESH_TOKEN_EXPIRATION_TIME = int(os.getenv("REFRESH_TOKEN_EXPIRATION_TIME"))
JWT_ALG = 'HS256'

# Google API Creds
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_CLIENT_REDIRECT_URL = os.getenv("GOOGLE_CLIENT_REDIRECT_URL")

RATE_LIMIT_DURATION = int(os.getenv('RATE_LIMIT_DURATION'))
RATE_LIMIT_REQUESTS = int(os.getenv('RATE_LIMIT_REQUESTS'))