from service.meta.auth_service_meta import AuthServiceMeta
from service.meta.post_service_meta import PostServiceMeta
from service.meta.user_service_meta import UserServiceMeta
from service.meta.task_service_meta import TaskServiceMeta
from service.meta.information_service_meta import InformationServiceMeta